Grr browse improvements
iossifovlab/gpf pull request #443
Opened 2023-04-25 11:44 UTC by livovachkov

## Background and aim

The improvements can be split into two subtasks. With migration into YAML, the idea is to transition the GRR definition into YAML format as the first task and the second is to make printing of the GRR default behavior.

## Implementation

Closes #434.

2023-04-25 12:00 UTC, lchorbadjiev requested changes
It is supposed that when we print the GRR definition, we should print it in YAML format, not as a dictionary.

Probably you could use something like `yaml.safe_dump`.

2023-04-25 12:15 UTC, iordanivanov requested changes
~~Running `grr_browse` still prints the configuration as a dict instead of a YAML-formatted string.~~

Resolved.

2023-04-27 06:15 UTC, lchorbadjiev requested changes
Please check the changes requested in the comments.

2023-04-27 06:15 UTC, lchorbadjiev commented on dae/dae/genomic_resources/cli.py
> +    print(yaml.dump(definition))
Always prefer `safe_dump` instead of `dump`.  Consider using `sort_keys=False` for keeping the GRR definition close to the original.

2023-04-27 06:15 UTC, lchorbadjiev commented on dae/dae/genomic_resources/tests/test_cli_browse.py
> +        "Working with GRR definition: " + str(repo_def) + "\n" \
When constructing strings always prefer using f-strings. Don't use `+` for strings.

2023-04-27 12:49 UTC, lchorbadjiev approved these changes

2023-04-28 08:47 UTC, iordanivanov approved these changes

2023-04-28 08:48 UTC, merged