update login and reset password ui
iossifovlab/gpf pull request #497
Opened 2023-07-25 09:54 UTC by IlinaGergova

## Background

Login page needed design improvements.

## Aim

To change the design.

## Implementation

Change design of login page, reset password page and forgotten password page.

2023-07-25 10:33 UTC, IvoStefanov approved these changes

2023-07-27 13:44 UTC, joankosev requested changes
1) change font-size to 16px for the "Email:", "Password" ;
and 14px for "Forgotten password"
2) change forgotten password color to #0645ad
3) consider adding hover css on forgotten password (underline)
4) reduce distance between last input field and the submit button, because it looks a bit odd in the reset password page (maybe change it only there? not sure how it's best)

2023-07-27 13:52 UTC, joankosev commented
submitting a forgotten password request leads to an error
ConnectionRefusedError at /api/v3/users/forgotten_password

2023-08-02 06:55 UTC, livovachkov approved these changes

2023-08-02 10:17 UTC, merged